### ISSUE TITLE
Missing tools

### ISSUE THREAD

**Issue by soholt** [diyelectromusic/picodexed#1]
./Synth_Dexed/tools/sysex2c.py seem to be missing and 
https://github.com/diyelectromusic/picodexed/blob/main/getvoices.sh
leaves src/voices.h with 0 bytes

**Comment by diyelectromusic** [comment]
That is part of Synth_Dexed (or was last time I looked! :))

Have you run getsubmod.sh to get Synth_Dexed?

Kevin

**Comment by soholt** [comment]
My bad, I didn't properly check the output of getsubmod.sh.. It has one too many dots on the first line ;)
Thanks, Gin

**Comment by diyelectromusic** [comment]
Oops!  I'll fix that :)

Thanks,
Kevin

**Comment by diyelectromusic** [comment]
Fixed in https://github.com/diyelectromusic/picodexed/commit/ef7928f12d60ffb9b97edde68b00b043b8972ce9
