### ISSUE TITLE
Connecting Picodexed directly to MIDI-synth

### ISSUE THREAD

**Issue by mwedmark** [diyelectromusic/picodexed#3]
I get sound when using Picodexed as device in LMMS in windows. Working just fine, nice to play some classic MIDI-files!
When I connect using the same cable as I use for my Zynthian instance (running on a PI4) no MIDI-traffic is handled..
I guess that in this scenario, the two devices switch place and what need to happen is that Picodexed need to become the USB host and the keyboard USB device to that host. Is this possible with the current code? That would be really dope.
I guess otherwise you could have a computer in between handling both listening to MIDI-in from Synth and redirecting that to MIDI-out to PicoDexed.. nore of less just a pass-through.

Another question is: when running 16 tones poly, would it be possible to split those into 2*8 and have 2 instances with different sounds running at the same time? Also does it currently support panning?

**Comment by diyelectromusic** [comment]
The Pico doesn't do USB host very well, so no, that isn't implemented right now.

I have a number of projects on my blog related to various MIDI USB to serial routing, so some of those might help sitting in between - see https://diyelectromusic.com/2022/03/22/arduino-and-usb-midi/.

The Pico isn't really powerful enough for two tone generators or a stereo output (with panning), even with just 8 note polyphony.  If you want to get going down that route then MiniDexed on a cheap Pi (3A or Zero 2) is probably the way to go.

Kevin

**Comment by mwedmark** [comment]
OK thank you. I'm not an expert here so good to get some info!
Yea Dexed is included in Zynthian so I already have that running on my PI4 via same MIDI-synth actually in Host-mode. So no worries. I just love the directness of the sound creation when running bare-metal as in PicoDexed. Also interesting to compare mixing music from picoDexed together with soft synths in LMMS on my PC.. I need to start the sound of softsynths several 1/192 earlier to get good sync because of extra latency. Even worse when running Zynthian on PI4. But these are really cool open-source projects anyways.

**Comment by diyelectromusic** [comment]
MiniDexed is a bare metal Raspberry Pi 8 tone generator DX7, so might be worth a look if you've not seen it already.  It's also a lot more developed than what I've done here, which is mostly just a bit of messing around :)
